[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Partición con espacio para app + LittleFS
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson@^7
    https://github.com/tzapu/WiFiManager.git
